# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Personal Website Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Create Release
        uses: ncipollo/release-action@v1.13.0
        with:
          makeLatest: true

      - name: Set up Node 16
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: Set up .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'
          dotnet-quality: 'preview'

      - name: Setup .NET WASM
        run: dotnet workload install wasm-tools

      - name: Restore Git Submodules
        run: git submodule update --init --recursive

      - name: Restore .NET Dependencies
        run: dotnet restore "${{ env.WORKING_DIRECTORY }}"
          
      - name: Restore NPM Dependencies
        run: npm i
        
      - name: Package Website Resources
        run: npm run prod

      - name: Build Website
        run: dotnet build Server --configuration Release -r linux-x64 --self-contained true

      - name: Publish Website
        run: dotnet publish Server -c Release -r linux-x64 -o ${{env.DOTNET_ROOT}}/myapp --self-contained true

      - name: Upload Artifacts For Azure Deployment
        uses: actions/upload-artifact@v2
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp
  
  deploy:
    runs-on: macos-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    steps:
      - name: Download Artifacts For Azure Deployment
        uses: actions/download-artifact@v2
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'stryxus'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_BD1FC5CD84C44849BF70F9FC7220FB5F }}
          package: .
